server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: posts-v1
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - RewritePath=/api/v1/posts/(?<segment>.*), /posts/$\{segment}